[build]
  publish = "public"
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Explicitly disable framework detection
[build.processing]
  skip_processing = false

# Force static site deployment - no framework detection
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true

# Override any automatic framework detection
[context.production]
  command = "echo 'Static site - no build needed'"
  publish = "public"